### ISSUE TITLE
Bug found: Empty space not added when first word of a sentence goes to null on transform

### ISSUE THREAD

**Issue by arnavsharma93** [irshadbhat/python-irtrans#2]
``` python
from irtrans import transliterator
trn = transliterator(source='eng', target='hin')
sent = 'aese teri'
utf_sent = trn.transform(sent)
print utf_sent
```

output: 'तेरी'

**Comment by irshadbhat** [comment]
This has happened due of less training data for training the model. In this case model predicts NULL for all four characters of 'aese' (NULL is represented by _ in the model).

Suppose I've a word 'chaand' , transliteration is done character by character where feature vector for each character contains the character itself and its preceding and succeeding context. The classifier output will be like this:

c -> च 
h -> _
a -> ा
a -> _
n -> ँ
d -> द

Underscores are removed from final output. Now in case of 'aese', the model predicted '_' for all four characters and thus final output is an empty string. This issue can only be solved by increasing training data which I am planning to do soon. For now these cases can be handled by repeating the last character of the word ('aese' to 'aesee') to give an approximate transliteration.

**Comment by arnavsharma93** [comment]
Yes but the bug is not that. In the code written above, the output should be '  तेरी' but it eats up the ' ' if it is in the beginning of the sentence. Otherwise it works fine.

**Comment by irshadbhat** [comment]
Oh yes the white space should remain there. I missed it because I never thought that the system would predict empty string for any valid string. I've committed the necessary changes on git.

If you don't want to reinstall the package, do the following:
- Get path of rom2ind.py 

``` python
from irtrans import rom2ind
print rom2ind
<module 'irtrans.rom2ind' from '/usr/local/lib/python2.7/dist-packages/irtrans-0.1-py2.7-linux-x86_64.egg/irtrans/rom2ind.pyc'> 
```
- sudo vim `/usr/local/lib/python2.7/dist-packages/irtrans-0.1-py2.7-linux-x86_64.egg/irtrans/rom2ind.py`
- Replace last line (`return tlins.strip()`) with `return tlins.strip('\n')`.

Do the same for ind2rom.py

**Comment by arnavsharma93** [comment]
Thanks! :+1:
